namespace QuanLiBanCoffe
{
    partial class QuanLyNhanVien
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(QuanLyNhanVien));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.btn_Luu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_Them = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_Sua = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txt_MatKhau = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_DN = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_SDT = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_Ten = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_MaNV = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_Moi = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.cb_GioiTinh = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.grid_NhanVien = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.MaNV = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.TenNV = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.GioiTinh = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.SDT = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.TenNguoiDung = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.MatKhau = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.btn_Xoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label10 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.txt_TimKiem = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.grid_NhanVien)).BeginInit();
            this.SuspendLayout();
            // 
            // btn_Luu
            // 
            this.btn_Luu.AllowAnimations = true;
            this.btn_Luu.AllowMouseEffects = true;
            this.btn_Luu.AllowToggling = false;
            this.btn_Luu.AnimationSpeed = 200;
            this.btn_Luu.AutoGenerateColors = false;
            this.btn_Luu.AutoRoundBorders = false;
            this.btn_Luu.AutoSizeLeftIcon = true;
            this.btn_Luu.AutoSizeRightIcon = true;
            this.btn_Luu.BackColor = System.Drawing.Color.Transparent;
            this.btn_Luu.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.btn_Luu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_Luu.BackgroundImage")));
            this.btn_Luu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Luu.ButtonText = "Lưu";
            this.btn_Luu.ButtonTextMarginLeft = 0;
            this.btn_Luu.ColorContrastOnClick = 45;
            this.btn_Luu.ColorContrastOnHover = 45;
            this.btn_Luu.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_Luu.CustomizableEdges = borderEdges1;
            this.btn_Luu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Luu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Luu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Luu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Luu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_Luu.Font = new System.Drawing.Font("Inter V Semi Bold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_Luu.ForeColor = System.Drawing.Color.White;
            this.btn_Luu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_Luu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Luu.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_Luu.IconMarginLeft = 11;
            this.btn_Luu.IconPadding = 10;
            this.btn_Luu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_Luu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Luu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_Luu.IconSize = 60;
            this.btn_Luu.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_Luu.IdleBorderRadius = 10;
            this.btn_Luu.IdleBorderThickness = 1;
            this.btn_Luu.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.btn_Luu.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_Luu.IdleIconLeftImage")));
            this.btn_Luu.IdleIconRightImage = null;
            this.btn_Luu.IndicateFocus = false;
            this.btn_Luu.Location = new System.Drawing.Point(615, 196);
            this.btn_Luu.Name = "btn_Luu";
            this.btn_Luu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Luu.OnDisabledState.BorderRadius = 10;
            this.btn_Luu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Luu.OnDisabledState.BorderThickness = 1;
            this.btn_Luu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Luu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Luu.OnDisabledState.IconLeftImage = null;
            this.btn_Luu.OnDisabledState.IconRightImage = null;
            this.btn_Luu.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Luu.onHoverState.BorderRadius = 10;
            this.btn_Luu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Luu.onHoverState.BorderThickness = 1;
            this.btn_Luu.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(119)))), ((int)(((byte)(197)))));
            this.btn_Luu.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_Luu.onHoverState.IconLeftImage = null;
            this.btn_Luu.onHoverState.IconRightImage = null;
            this.btn_Luu.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Luu.OnIdleState.BorderRadius = 10;
            this.btn_Luu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Luu.OnIdleState.BorderThickness = 1;
            this.btn_Luu.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.btn_Luu.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_Luu.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_Luu.OnIdleState.IconLeftImage")));
            this.btn_Luu.OnIdleState.IconRightImage = null;
            this.btn_Luu.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Luu.OnPressedState.BorderRadius = 10;
            this.btn_Luu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Luu.OnPressedState.BorderThickness = 1;
            this.btn_Luu.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(145)))), ((int)(((byte)(208)))));
            this.btn_Luu.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_Luu.OnPressedState.IconLeftImage = null;
            this.btn_Luu.OnPressedState.IconRightImage = null;
            this.btn_Luu.Size = new System.Drawing.Size(105, 39);
            this.btn_Luu.TabIndex = 11;
            this.btn_Luu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_Luu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_Luu.TextMarginLeft = 0;
            this.btn_Luu.TextPadding = new System.Windows.Forms.Padding(13, 0, 0, 0);
            this.btn_Luu.UseDefaultRadiusAndThickness = true;
            this.btn_Luu.Click += new System.EventHandler(this.btn_Luu_Click);
            // 
            // btn_Them
            // 
            this.btn_Them.AllowAnimations = true;
            this.btn_Them.AllowMouseEffects = true;
            this.btn_Them.AllowToggling = false;
            this.btn_Them.AnimationSpeed = 200;
            this.btn_Them.AutoGenerateColors = false;
            this.btn_Them.AutoRoundBorders = false;
            this.btn_Them.AutoSizeLeftIcon = true;
            this.btn_Them.AutoSizeRightIcon = true;
            this.btn_Them.BackColor = System.Drawing.Color.Transparent;
            this.btn_Them.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.btn_Them.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_Them.BackgroundImage")));
            this.btn_Them.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Them.ButtonText = "Thêm";
            this.btn_Them.ButtonTextMarginLeft = 0;
            this.btn_Them.ColorContrastOnClick = 45;
            this.btn_Them.ColorContrastOnHover = 45;
            this.btn_Them.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_Them.CustomizableEdges = borderEdges2;
            this.btn_Them.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Them.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Them.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Them.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Them.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_Them.Font = new System.Drawing.Font("Inter V Semi Bold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_Them.ForeColor = System.Drawing.Color.White;
            this.btn_Them.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_Them.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Them.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_Them.IconMarginLeft = 11;
            this.btn_Them.IconPadding = 10;
            this.btn_Them.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_Them.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Them.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_Them.IconSize = 60;
            this.btn_Them.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_Them.IdleBorderRadius = 10;
            this.btn_Them.IdleBorderThickness = 1;
            this.btn_Them.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.btn_Them.IdleIconLeftImage = global::QuanLiBanCoffe.Properties.Resources.plus;
            this.btn_Them.IdleIconRightImage = null;
            this.btn_Them.IndicateFocus = false;
            this.btn_Them.Location = new System.Drawing.Point(75, 196);
            this.btn_Them.Name = "btn_Them";
            this.btn_Them.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Them.OnDisabledState.BorderRadius = 10;
            this.btn_Them.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Them.OnDisabledState.BorderThickness = 1;
            this.btn_Them.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Them.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Them.OnDisabledState.IconLeftImage = null;
            this.btn_Them.OnDisabledState.IconRightImage = null;
            this.btn_Them.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Them.onHoverState.BorderRadius = 10;
            this.btn_Them.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Them.onHoverState.BorderThickness = 1;
            this.btn_Them.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(119)))), ((int)(((byte)(197)))));
            this.btn_Them.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_Them.onHoverState.IconLeftImage = null;
            this.btn_Them.onHoverState.IconRightImage = null;
            this.btn_Them.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Them.OnIdleState.BorderRadius = 10;
            this.btn_Them.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Them.OnIdleState.BorderThickness = 1;
            this.btn_Them.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.btn_Them.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_Them.OnIdleState.IconLeftImage = global::QuanLiBanCoffe.Properties.Resources.plus;
            this.btn_Them.OnIdleState.IconRightImage = null;
            this.btn_Them.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Them.OnPressedState.BorderRadius = 10;
            this.btn_Them.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Them.OnPressedState.BorderThickness = 1;
            this.btn_Them.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(145)))), ((int)(((byte)(208)))));
            this.btn_Them.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_Them.OnPressedState.IconLeftImage = null;
            this.btn_Them.OnPressedState.IconRightImage = null;
            this.btn_Them.Size = new System.Drawing.Size(105, 39);
            this.btn_Them.TabIndex = 7;
            this.btn_Them.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_Them.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_Them.TextMarginLeft = 0;
            this.btn_Them.TextPadding = new System.Windows.Forms.Padding(7, 0, 0, 0);
            this.btn_Them.UseDefaultRadiusAndThickness = true;
            this.btn_Them.Click += new System.EventHandler(this.btn_Them_Click);
            // 
            // btn_Sua
            // 
            this.btn_Sua.AllowAnimations = true;
            this.btn_Sua.AllowMouseEffects = true;
            this.btn_Sua.AllowToggling = false;
            this.btn_Sua.AnimationSpeed = 200;
            this.btn_Sua.AutoGenerateColors = false;
            this.btn_Sua.AutoRoundBorders = false;
            this.btn_Sua.AutoSizeLeftIcon = true;
            this.btn_Sua.AutoSizeRightIcon = true;
            this.btn_Sua.BackColor = System.Drawing.Color.Transparent;
            this.btn_Sua.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.btn_Sua.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_Sua.BackgroundImage")));
            this.btn_Sua.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Sua.ButtonText = "Sửa";
            this.btn_Sua.ButtonTextMarginLeft = 0;
            this.btn_Sua.ColorContrastOnClick = 45;
            this.btn_Sua.ColorContrastOnHover = 45;
            this.btn_Sua.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_Sua.CustomizableEdges = borderEdges3;
            this.btn_Sua.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Sua.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Sua.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Sua.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Sua.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_Sua.Font = new System.Drawing.Font("Inter V Semi Bold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_Sua.ForeColor = System.Drawing.Color.White;
            this.btn_Sua.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_Sua.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Sua.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_Sua.IconMarginLeft = 11;
            this.btn_Sua.IconPadding = 10;
            this.btn_Sua.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_Sua.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Sua.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_Sua.IconSize = 60;
            this.btn_Sua.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_Sua.IdleBorderRadius = 10;
            this.btn_Sua.IdleBorderThickness = 1;
            this.btn_Sua.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.btn_Sua.IdleIconLeftImage = global::QuanLiBanCoffe.Properties.Resources.arrow1;
            this.btn_Sua.IdleIconRightImage = null;
            this.btn_Sua.IndicateFocus = false;
            this.btn_Sua.Location = new System.Drawing.Point(210, 196);
            this.btn_Sua.Name = "btn_Sua";
            this.btn_Sua.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Sua.OnDisabledState.BorderRadius = 10;
            this.btn_Sua.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Sua.OnDisabledState.BorderThickness = 1;
            this.btn_Sua.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Sua.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Sua.OnDisabledState.IconLeftImage = null;
            this.btn_Sua.OnDisabledState.IconRightImage = null;
            this.btn_Sua.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Sua.onHoverState.BorderRadius = 10;
            this.btn_Sua.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Sua.onHoverState.BorderThickness = 1;
            this.btn_Sua.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(119)))), ((int)(((byte)(197)))));
            this.btn_Sua.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_Sua.onHoverState.IconLeftImage = null;
            this.btn_Sua.onHoverState.IconRightImage = null;
            this.btn_Sua.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Sua.OnIdleState.BorderRadius = 10;
            this.btn_Sua.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Sua.OnIdleState.BorderThickness = 1;
            this.btn_Sua.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.btn_Sua.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_Sua.OnIdleState.IconLeftImage = global::QuanLiBanCoffe.Properties.Resources.arrow1;
            this.btn_Sua.OnIdleState.IconRightImage = null;
            this.btn_Sua.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Sua.OnPressedState.BorderRadius = 10;
            this.btn_Sua.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Sua.OnPressedState.BorderThickness = 1;
            this.btn_Sua.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(145)))), ((int)(((byte)(208)))));
            this.btn_Sua.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_Sua.OnPressedState.IconLeftImage = null;
            this.btn_Sua.OnPressedState.IconRightImage = null;
            this.btn_Sua.Size = new System.Drawing.Size(105, 39);
            this.btn_Sua.TabIndex = 8;
            this.btn_Sua.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_Sua.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_Sua.TextMarginLeft = 0;
            this.btn_Sua.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.btn_Sua.UseDefaultRadiusAndThickness = true;
            this.btn_Sua.Click += new System.EventHandler(this.btn_Sua_Click);
            // 
            // txt_MatKhau
            // 
            this.txt_MatKhau.AcceptsReturn = false;
            this.txt_MatKhau.AcceptsTab = false;
            this.txt_MatKhau.AnimationSpeed = 200;
            this.txt_MatKhau.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_MatKhau.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_MatKhau.BackColor = System.Drawing.Color.Transparent;
            this.txt_MatKhau.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_MatKhau.BackgroundImage")));
            this.txt_MatKhau.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_MatKhau.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_MatKhau.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_MatKhau.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_MatKhau.BorderRadius = 1;
            this.txt_MatKhau.BorderThickness = 1;
            this.txt_MatKhau.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_MatKhau.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_MatKhau.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txt_MatKhau.DefaultText = "";
            this.txt_MatKhau.FillColor = System.Drawing.Color.White;
            this.txt_MatKhau.HideSelection = true;
            this.txt_MatKhau.IconLeft = null;
            this.txt_MatKhau.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_MatKhau.IconPadding = 10;
            this.txt_MatKhau.IconRight = null;
            this.txt_MatKhau.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_MatKhau.Lines = new string[0];
            this.txt_MatKhau.Location = new System.Drawing.Point(352, 149);
            this.txt_MatKhau.MaxLength = 100;
            this.txt_MatKhau.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_MatKhau.Modified = false;
            this.txt_MatKhau.Multiline = false;
            this.txt_MatKhau.Name = "txt_MatKhau";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_MatKhau.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_MatKhau.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_MatKhau.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_MatKhau.OnIdleState = stateProperties4;
            this.txt_MatKhau.Padding = new System.Windows.Forms.Padding(3);
            this.txt_MatKhau.PasswordChar = '\0';
            this.txt_MatKhau.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_MatKhau.PlaceholderText = "";
            this.txt_MatKhau.ReadOnly = false;
            this.txt_MatKhau.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_MatKhau.SelectedText = "";
            this.txt_MatKhau.SelectionLength = 0;
            this.txt_MatKhau.SelectionStart = 0;
            this.txt_MatKhau.ShortcutsEnabled = true;
            this.txt_MatKhau.Size = new System.Drawing.Size(111, 38);
            this.txt_MatKhau.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_MatKhau.TabIndex = 6;
            this.txt_MatKhau.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_MatKhau.TextMarginBottom = 0;
            this.txt_MatKhau.TextMarginLeft = 3;
            this.txt_MatKhau.TextMarginTop = 0;
            this.txt_MatKhau.TextPlaceholder = "";
            this.txt_MatKhau.UseSystemPasswordChar = false;
            this.txt_MatKhau.WordWrap = true;
            // 
            // txt_DN
            // 
            this.txt_DN.AcceptsReturn = false;
            this.txt_DN.AcceptsTab = false;
            this.txt_DN.AnimationSpeed = 200;
            this.txt_DN.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_DN.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_DN.BackColor = System.Drawing.Color.Transparent;
            this.txt_DN.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_DN.BackgroundImage")));
            this.txt_DN.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_DN.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_DN.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_DN.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_DN.BorderRadius = 1;
            this.txt_DN.BorderThickness = 1;
            this.txt_DN.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_DN.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_DN.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txt_DN.DefaultText = "";
            this.txt_DN.FillColor = System.Drawing.Color.White;
            this.txt_DN.HideSelection = true;
            this.txt_DN.IconLeft = null;
            this.txt_DN.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_DN.IconPadding = 10;
            this.txt_DN.IconRight = null;
            this.txt_DN.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_DN.Lines = new string[0];
            this.txt_DN.Location = new System.Drawing.Point(670, 79);
            this.txt_DN.MaxLength = 100;
            this.txt_DN.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_DN.Modified = false;
            this.txt_DN.Multiline = false;
            this.txt_DN.Name = "txt_DN";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_DN.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_DN.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_DN.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_DN.OnIdleState = stateProperties8;
            this.txt_DN.Padding = new System.Windows.Forms.Padding(3);
            this.txt_DN.PasswordChar = '\0';
            this.txt_DN.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_DN.PlaceholderText = "";
            this.txt_DN.ReadOnly = false;
            this.txt_DN.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_DN.SelectedText = "";
            this.txt_DN.SelectionLength = 0;
            this.txt_DN.SelectionStart = 0;
            this.txt_DN.ShortcutsEnabled = true;
            this.txt_DN.Size = new System.Drawing.Size(111, 38);
            this.txt_DN.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_DN.TabIndex = 5;
            this.txt_DN.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_DN.TextMarginBottom = 0;
            this.txt_DN.TextMarginLeft = 3;
            this.txt_DN.TextMarginTop = 0;
            this.txt_DN.TextPlaceholder = "";
            this.txt_DN.UseSystemPasswordChar = false;
            this.txt_DN.WordWrap = true;
            // 
            // txt_SDT
            // 
            this.txt_SDT.AcceptsReturn = false;
            this.txt_SDT.AcceptsTab = false;
            this.txt_SDT.AnimationSpeed = 200;
            this.txt_SDT.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_SDT.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_SDT.BackColor = System.Drawing.Color.Transparent;
            this.txt_SDT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_SDT.BackgroundImage")));
            this.txt_SDT.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_SDT.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_SDT.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_SDT.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_SDT.BorderRadius = 1;
            this.txt_SDT.BorderThickness = 1;
            this.txt_SDT.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_SDT.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SDT.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txt_SDT.DefaultText = "";
            this.txt_SDT.FillColor = System.Drawing.Color.White;
            this.txt_SDT.HideSelection = true;
            this.txt_SDT.IconLeft = null;
            this.txt_SDT.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SDT.IconPadding = 10;
            this.txt_SDT.IconRight = null;
            this.txt_SDT.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SDT.Lines = new string[0];
            this.txt_SDT.Location = new System.Drawing.Point(514, 80);
            this.txt_SDT.MaxLength = 10;
            this.txt_SDT.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_SDT.Modified = false;
            this.txt_SDT.Multiline = false;
            this.txt_SDT.Name = "txt_SDT";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SDT.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_SDT.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SDT.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SDT.OnIdleState = stateProperties12;
            this.txt_SDT.Padding = new System.Windows.Forms.Padding(3);
            this.txt_SDT.PasswordChar = '\0';
            this.txt_SDT.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_SDT.PlaceholderText = "";
            this.txt_SDT.ReadOnly = false;
            this.txt_SDT.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_SDT.SelectedText = "";
            this.txt_SDT.SelectionLength = 0;
            this.txt_SDT.SelectionStart = 0;
            this.txt_SDT.ShortcutsEnabled = true;
            this.txt_SDT.Size = new System.Drawing.Size(111, 38);
            this.txt_SDT.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_SDT.TabIndex = 4;
            this.txt_SDT.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_SDT.TextMarginBottom = 0;
            this.txt_SDT.TextMarginLeft = 3;
            this.txt_SDT.TextMarginTop = 0;
            this.txt_SDT.TextPlaceholder = "";
            this.txt_SDT.UseSystemPasswordChar = false;
            this.txt_SDT.WordWrap = true;
            this.txt_SDT.TextChanged += new System.EventHandler(this.txt_SDT_TextChanged);
            this.txt_SDT.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_SDT_KeyPress);
            // 
            // txt_Ten
            // 
            this.txt_Ten.AcceptsReturn = false;
            this.txt_Ten.AcceptsTab = false;
            this.txt_Ten.AnimationSpeed = 200;
            this.txt_Ten.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Ten.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Ten.BackColor = System.Drawing.Color.Transparent;
            this.txt_Ten.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Ten.BackgroundImage")));
            this.txt_Ten.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_Ten.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_Ten.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_Ten.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Ten.BorderRadius = 1;
            this.txt_Ten.BorderThickness = 1;
            this.txt_Ten.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Ten.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Ten.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txt_Ten.DefaultText = "";
            this.txt_Ten.FillColor = System.Drawing.Color.White;
            this.txt_Ten.HideSelection = true;
            this.txt_Ten.IconLeft = null;
            this.txt_Ten.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Ten.IconPadding = 10;
            this.txt_Ten.IconRight = null;
            this.txt_Ten.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Ten.Lines = new string[0];
            this.txt_Ten.Location = new System.Drawing.Point(190, 80);
            this.txt_Ten.MaxLength = 100;
            this.txt_Ten.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_Ten.Modified = false;
            this.txt_Ten.Multiline = false;
            this.txt_Ten.Name = "txt_Ten";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Ten.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_Ten.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Ten.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Ten.OnIdleState = stateProperties16;
            this.txt_Ten.Padding = new System.Windows.Forms.Padding(3);
            this.txt_Ten.PasswordChar = '\0';
            this.txt_Ten.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Ten.PlaceholderText = "";
            this.txt_Ten.ReadOnly = false;
            this.txt_Ten.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Ten.SelectedText = "";
            this.txt_Ten.SelectionLength = 0;
            this.txt_Ten.SelectionStart = 0;
            this.txt_Ten.ShortcutsEnabled = true;
            this.txt_Ten.Size = new System.Drawing.Size(125, 38);
            this.txt_Ten.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_Ten.TabIndex = 2;
            this.txt_Ten.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_Ten.TextMarginBottom = 0;
            this.txt_Ten.TextMarginLeft = 3;
            this.txt_Ten.TextMarginTop = 0;
            this.txt_Ten.TextPlaceholder = "";
            this.txt_Ten.UseSystemPasswordChar = false;
            this.txt_Ten.WordWrap = true;
            // 
            // txt_MaNV
            // 
            this.txt_MaNV.AcceptsReturn = false;
            this.txt_MaNV.AcceptsTab = false;
            this.txt_MaNV.AnimationSpeed = 200;
            this.txt_MaNV.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_MaNV.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_MaNV.BackColor = System.Drawing.Color.Transparent;
            this.txt_MaNV.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_MaNV.BackgroundImage")));
            this.txt_MaNV.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_MaNV.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_MaNV.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_MaNV.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_MaNV.BorderRadius = 1;
            this.txt_MaNV.BorderThickness = 1;
            this.txt_MaNV.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_MaNV.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_MaNV.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txt_MaNV.DefaultText = "";
            this.txt_MaNV.Enabled = false;
            this.txt_MaNV.FillColor = System.Drawing.Color.White;
            this.txt_MaNV.HideSelection = true;
            this.txt_MaNV.IconLeft = null;
            this.txt_MaNV.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_MaNV.IconPadding = 10;
            this.txt_MaNV.IconRight = null;
            this.txt_MaNV.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_MaNV.Lines = new string[0];
            this.txt_MaNV.Location = new System.Drawing.Point(28, 80);
            this.txt_MaNV.MaxLength = 256;
            this.txt_MaNV.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_MaNV.Modified = false;
            this.txt_MaNV.Multiline = false;
            this.txt_MaNV.Name = "txt_MaNV";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_MaNV.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_MaNV.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_MaNV.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_MaNV.OnIdleState = stateProperties20;
            this.txt_MaNV.Padding = new System.Windows.Forms.Padding(3);
            this.txt_MaNV.PasswordChar = '\0';
            this.txt_MaNV.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_MaNV.PlaceholderText = "";
            this.txt_MaNV.ReadOnly = false;
            this.txt_MaNV.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_MaNV.SelectedText = "";
            this.txt_MaNV.SelectionLength = 0;
            this.txt_MaNV.SelectionStart = 0;
            this.txt_MaNV.ShortcutsEnabled = true;
            this.txt_MaNV.Size = new System.Drawing.Size(111, 38);
            this.txt_MaNV.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_MaNV.TabIndex = 1;
            this.txt_MaNV.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_MaNV.TextMarginBottom = 0;
            this.txt_MaNV.TextMarginLeft = 3;
            this.txt_MaNV.TextMarginTop = 0;
            this.txt_MaNV.TextPlaceholder = "";
            this.txt_MaNV.UseSystemPasswordChar = false;
            this.txt_MaNV.WordWrap = true;
            // 
            // btn_Moi
            // 
            this.btn_Moi.AllowAnimations = true;
            this.btn_Moi.AllowMouseEffects = true;
            this.btn_Moi.AllowToggling = false;
            this.btn_Moi.AnimationSpeed = 200;
            this.btn_Moi.AutoGenerateColors = false;
            this.btn_Moi.AutoRoundBorders = false;
            this.btn_Moi.AutoSizeLeftIcon = true;
            this.btn_Moi.AutoSizeRightIcon = true;
            this.btn_Moi.BackColor = System.Drawing.Color.Transparent;
            this.btn_Moi.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.btn_Moi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_Moi.BackgroundImage")));
            this.btn_Moi.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Moi.ButtonText = "Làm mới";
            this.btn_Moi.ButtonTextMarginLeft = 0;
            this.btn_Moi.ColorContrastOnClick = 45;
            this.btn_Moi.ColorContrastOnHover = 45;
            this.btn_Moi.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_Moi.CustomizableEdges = borderEdges4;
            this.btn_Moi.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Moi.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Moi.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Moi.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Moi.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_Moi.Font = new System.Drawing.Font("Inter V Semi Bold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_Moi.ForeColor = System.Drawing.Color.White;
            this.btn_Moi.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_Moi.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Moi.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_Moi.IconMarginLeft = 11;
            this.btn_Moi.IconPadding = 10;
            this.btn_Moi.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_Moi.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Moi.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_Moi.IconSize = 60;
            this.btn_Moi.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_Moi.IdleBorderRadius = 10;
            this.btn_Moi.IdleBorderThickness = 1;
            this.btn_Moi.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.btn_Moi.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_Moi.IdleIconLeftImage")));
            this.btn_Moi.IdleIconRightImage = null;
            this.btn_Moi.IndicateFocus = false;
            this.btn_Moi.Location = new System.Drawing.Point(480, 196);
            this.btn_Moi.Name = "btn_Moi";
            this.btn_Moi.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Moi.OnDisabledState.BorderRadius = 10;
            this.btn_Moi.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Moi.OnDisabledState.BorderThickness = 1;
            this.btn_Moi.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Moi.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Moi.OnDisabledState.IconLeftImage = null;
            this.btn_Moi.OnDisabledState.IconRightImage = null;
            this.btn_Moi.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Moi.onHoverState.BorderRadius = 10;
            this.btn_Moi.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Moi.onHoverState.BorderThickness = 1;
            this.btn_Moi.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(119)))), ((int)(((byte)(197)))));
            this.btn_Moi.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_Moi.onHoverState.IconLeftImage = null;
            this.btn_Moi.onHoverState.IconRightImage = null;
            this.btn_Moi.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Moi.OnIdleState.BorderRadius = 10;
            this.btn_Moi.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Moi.OnIdleState.BorderThickness = 1;
            this.btn_Moi.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.btn_Moi.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_Moi.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_Moi.OnIdleState.IconLeftImage")));
            this.btn_Moi.OnIdleState.IconRightImage = null;
            this.btn_Moi.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Moi.OnPressedState.BorderRadius = 10;
            this.btn_Moi.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Moi.OnPressedState.BorderThickness = 1;
            this.btn_Moi.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(145)))), ((int)(((byte)(208)))));
            this.btn_Moi.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_Moi.OnPressedState.IconLeftImage = null;
            this.btn_Moi.OnPressedState.IconRightImage = null;
            this.btn_Moi.Size = new System.Drawing.Size(105, 39);
            this.btn_Moi.TabIndex = 10;
            this.btn_Moi.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_Moi.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_Moi.TextMarginLeft = 0;
            this.btn_Moi.TextPadding = new System.Windows.Forms.Padding(13, 0, 0, 0);
            this.btn_Moi.UseDefaultRadiusAndThickness = true;
            this.btn_Moi.Click += new System.EventHandler(this.btn_Moi_Click_1);
            // 
            // cb_GioiTinh
            // 
            this.cb_GioiTinh.BackColor = System.Drawing.Color.Transparent;
            this.cb_GioiTinh.BackgroundColor = System.Drawing.Color.White;
            this.cb_GioiTinh.BorderColor = System.Drawing.Color.Silver;
            this.cb_GioiTinh.BorderRadius = 1;
            this.cb_GioiTinh.Color = System.Drawing.Color.Silver;
            this.cb_GioiTinh.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cb_GioiTinh.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cb_GioiTinh.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cb_GioiTinh.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cb_GioiTinh.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cb_GioiTinh.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cb_GioiTinh.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cb_GioiTinh.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cb_GioiTinh.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cb_GioiTinh.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cb_GioiTinh.FillDropDown = true;
            this.cb_GioiTinh.FillIndicator = false;
            this.cb_GioiTinh.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cb_GioiTinh.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cb_GioiTinh.ForeColor = System.Drawing.Color.Black;
            this.cb_GioiTinh.FormattingEnabled = true;
            this.cb_GioiTinh.Icon = null;
            this.cb_GioiTinh.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cb_GioiTinh.IndicatorColor = System.Drawing.Color.Gray;
            this.cb_GioiTinh.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cb_GioiTinh.ItemBackColor = System.Drawing.Color.White;
            this.cb_GioiTinh.ItemBorderColor = System.Drawing.Color.White;
            this.cb_GioiTinh.ItemForeColor = System.Drawing.Color.Black;
            this.cb_GioiTinh.ItemHeight = 26;
            this.cb_GioiTinh.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cb_GioiTinh.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cb_GioiTinh.Items.AddRange(new object[] {
            "Nam",
            "Nữ"});
            this.cb_GioiTinh.ItemTopMargin = 3;
            this.cb_GioiTinh.Location = new System.Drawing.Point(352, 84);
            this.cb_GioiTinh.Name = "cb_GioiTinh";
            this.cb_GioiTinh.Size = new System.Drawing.Size(111, 32);
            this.cb_GioiTinh.TabIndex = 3;
            this.cb_GioiTinh.Text = null;
            this.cb_GioiTinh.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cb_GioiTinh.TextLeftMargin = 5;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 5;
            this.bunifuElipse1.TargetControl = this.grid_NhanVien;
            // 
            // grid_NhanVien
            // 
            this.grid_NhanVien.AllowCustomTheming = true;
            this.grid_NhanVien.AllowUserToAddRows = false;
            this.grid_NhanVien.AllowUserToDeleteRows = false;
            this.grid_NhanVien.AllowUserToResizeColumns = false;
            this.grid_NhanVien.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(232)))), ((int)(((byte)(191)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.grid_NhanVien.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.grid_NhanVien.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.grid_NhanVien.BackgroundColor = System.Drawing.Color.IndianRed;
            this.grid_NhanVien.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.grid_NhanVien.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None;
            this.grid_NhanVien.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.Orange;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.DarkViolet;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(132)))), ((int)(((byte)(0)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.grid_NhanVien.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.grid_NhanVien.ColumnHeadersHeight = 40;
            this.grid_NhanVien.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.MaNV,
            this.TenNV,
            this.GioiTinh,
            this.SDT,
            this.TenNguoiDung,
            this.MatKhau});
            this.grid_NhanVien.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(232)))), ((int)(((byte)(191)))));
            this.grid_NhanVien.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.grid_NhanVien.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.grid_NhanVien.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(201)))), ((int)(((byte)(102)))));
            this.grid_NhanVien.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.grid_NhanVien.CurrentTheme.BackColor = System.Drawing.Color.Orange;
            this.grid_NhanVien.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(226)))), ((int)(((byte)(173)))));
            this.grid_NhanVien.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.Orange;
            this.grid_NhanVien.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grid_NhanVien.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.DarkViolet;
            this.grid_NhanVien.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(132)))), ((int)(((byte)(0)))));
            this.grid_NhanVien.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.grid_NhanVien.CurrentTheme.Name = null;
            this.grid_NhanVien.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.Orange;
            this.grid_NhanVien.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.grid_NhanVien.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.grid_NhanVien.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(201)))), ((int)(((byte)(102)))));
            this.grid_NhanVien.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.Orange;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(201)))), ((int)(((byte)(102)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.grid_NhanVien.DefaultCellStyle = dataGridViewCellStyle3;
            this.grid_NhanVien.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.grid_NhanVien.EnableHeadersVisualStyles = false;
            this.grid_NhanVien.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(226)))), ((int)(((byte)(173)))));
            this.grid_NhanVien.HeaderBackColor = System.Drawing.Color.Orange;
            this.grid_NhanVien.HeaderBgColor = System.Drawing.Color.Empty;
            this.grid_NhanVien.HeaderForeColor = System.Drawing.Color.DarkViolet;
            this.grid_NhanVien.Location = new System.Drawing.Point(0, 239);
            this.grid_NhanVien.Name = "grid_NhanVien";
            this.grid_NhanVien.ReadOnly = true;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Segoe UI", 12.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.grid_NhanVien.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.grid_NhanVien.RowHeadersVisible = false;
            this.grid_NhanVien.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.grid_NhanVien.RowTemplate.DividerHeight = 1;
            this.grid_NhanVien.RowTemplate.Height = 40;
            this.grid_NhanVien.RowTemplate.Resizable = System.Windows.Forms.DataGridViewTriState.False;
            this.grid_NhanVien.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.grid_NhanVien.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.grid_NhanVien.Size = new System.Drawing.Size(852, 291);
            this.grid_NhanVien.TabIndex = 12;
            this.grid_NhanVien.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Orange;
            this.grid_NhanVien.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.grid_NhanVien_CellClick);
            // 
            // MaNV
            // 
            this.MaNV.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.MaNV.DataPropertyName = "MaNV";
            this.MaNV.FillWeight = 28.62944F;
            this.MaNV.HeaderText = "Mã Nhân Viên";
            this.MaNV.Name = "MaNV";
            this.MaNV.ReadOnly = true;
            this.MaNV.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.MaNV.Width = 120;
            // 
            // TenNV
            // 
            this.TenNV.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.TenNV.DataPropertyName = "TenNV";
            this.TenNV.FillWeight = 456.8528F;
            this.TenNV.HeaderText = "Tên Nhân Viên";
            this.TenNV.Name = "TenNV";
            this.TenNV.ReadOnly = true;
            this.TenNV.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.TenNV.Width = 200;
            // 
            // GioiTinh
            // 
            this.GioiTinh.DataPropertyName = "GioiTinh";
            this.GioiTinh.FillWeight = 28.62944F;
            this.GioiTinh.HeaderText = "Giới Tính";
            this.GioiTinh.Name = "GioiTinh";
            this.GioiTinh.ReadOnly = true;
            this.GioiTinh.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            // 
            // SDT
            // 
            this.SDT.DataPropertyName = "SDT";
            this.SDT.FillWeight = 28.62944F;
            this.SDT.HeaderText = "SĐT";
            this.SDT.Name = "SDT";
            this.SDT.ReadOnly = true;
            this.SDT.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            // 
            // TenNguoiDung
            // 
            this.TenNguoiDung.DataPropertyName = "TenNguoiDung";
            this.TenNguoiDung.FillWeight = 28.62944F;
            this.TenNguoiDung.HeaderText = "Tên Đăng Nhập";
            this.TenNguoiDung.Name = "TenNguoiDung";
            this.TenNguoiDung.ReadOnly = true;
            this.TenNguoiDung.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            // 
            // MatKhau
            // 
            this.MatKhau.DataPropertyName = "MatKhau";
            this.MatKhau.FillWeight = 28.62944F;
            this.MatKhau.HeaderText = "Mật Khẩu";
            this.MatKhau.Name = "MatKhau";
            this.MatKhau.ReadOnly = true;
            this.MatKhau.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            // 
            // btn_Xoa
            // 
            this.btn_Xoa.AllowAnimations = true;
            this.btn_Xoa.AllowMouseEffects = true;
            this.btn_Xoa.AllowToggling = false;
            this.btn_Xoa.AnimationSpeed = 200;
            this.btn_Xoa.AutoGenerateColors = false;
            this.btn_Xoa.AutoRoundBorders = false;
            this.btn_Xoa.AutoSizeLeftIcon = true;
            this.btn_Xoa.AutoSizeRightIcon = true;
            this.btn_Xoa.BackColor = System.Drawing.Color.Transparent;
            this.btn_Xoa.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.btn_Xoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_Xoa.BackgroundImage")));
            this.btn_Xoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Xoa.ButtonText = "Xoá";
            this.btn_Xoa.ButtonTextMarginLeft = 0;
            this.btn_Xoa.ColorContrastOnClick = 45;
            this.btn_Xoa.ColorContrastOnHover = 45;
            this.btn_Xoa.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btn_Xoa.CustomizableEdges = borderEdges5;
            this.btn_Xoa.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Xoa.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Xoa.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Xoa.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Xoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_Xoa.Font = new System.Drawing.Font("Inter V Semi Bold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_Xoa.ForeColor = System.Drawing.Color.White;
            this.btn_Xoa.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_Xoa.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Xoa.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_Xoa.IconMarginLeft = 11;
            this.btn_Xoa.IconPadding = 10;
            this.btn_Xoa.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_Xoa.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Xoa.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_Xoa.IconSize = 60;
            this.btn_Xoa.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_Xoa.IdleBorderRadius = 10;
            this.btn_Xoa.IdleBorderThickness = 1;
            this.btn_Xoa.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.btn_Xoa.IdleIconLeftImage = global::QuanLiBanCoffe.Properties.Resources.bin;
            this.btn_Xoa.IdleIconRightImage = null;
            this.btn_Xoa.IndicateFocus = false;
            this.btn_Xoa.Location = new System.Drawing.Point(345, 196);
            this.btn_Xoa.Name = "btn_Xoa";
            this.btn_Xoa.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Xoa.OnDisabledState.BorderRadius = 10;
            this.btn_Xoa.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Xoa.OnDisabledState.BorderThickness = 1;
            this.btn_Xoa.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Xoa.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Xoa.OnDisabledState.IconLeftImage = null;
            this.btn_Xoa.OnDisabledState.IconRightImage = null;
            this.btn_Xoa.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Xoa.onHoverState.BorderRadius = 10;
            this.btn_Xoa.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Xoa.onHoverState.BorderThickness = 1;
            this.btn_Xoa.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(119)))), ((int)(((byte)(197)))));
            this.btn_Xoa.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_Xoa.onHoverState.IconLeftImage = null;
            this.btn_Xoa.onHoverState.IconRightImage = null;
            this.btn_Xoa.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Xoa.OnIdleState.BorderRadius = 10;
            this.btn_Xoa.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Xoa.OnIdleState.BorderThickness = 1;
            this.btn_Xoa.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(81)))), ((int)(((byte)(181)))));
            this.btn_Xoa.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_Xoa.OnIdleState.IconLeftImage = global::QuanLiBanCoffe.Properties.Resources.bin;
            this.btn_Xoa.OnIdleState.IconRightImage = null;
            this.btn_Xoa.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Xoa.OnPressedState.BorderRadius = 10;
            this.btn_Xoa.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Xoa.OnPressedState.BorderThickness = 1;
            this.btn_Xoa.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(145)))), ((int)(((byte)(208)))));
            this.btn_Xoa.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_Xoa.OnPressedState.IconLeftImage = null;
            this.btn_Xoa.OnPressedState.IconRightImage = null;
            this.btn_Xoa.Size = new System.Drawing.Size(105, 39);
            this.btn_Xoa.TabIndex = 9;
            this.btn_Xoa.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_Xoa.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_Xoa.TextMarginLeft = 0;
            this.btn_Xoa.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.btn_Xoa.UseDefaultRadiusAndThickness = true;
            this.btn_Xoa.Click += new System.EventHandler(this.btn_Xoa_Click);
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Inter V Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.Location = new System.Drawing.Point(666, 58);
            this.label10.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(127, 19);
            this.label10.TabIndex = 76;
            this.label10.Text = "Tên Đăng Nhập";
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Inter V Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.Location = new System.Drawing.Point(348, 58);
            this.label9.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(78, 19);
            this.label9.TabIndex = 73;
            this.label9.Text = "Giới Tính";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Inter V Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(186, 58);
            this.label8.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(120, 19);
            this.label8.TabIndex = 72;
            this.label8.Text = "Tên Nhân Viên";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Inter V Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(510, 58);
            this.label6.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(41, 19);
            this.label6.TabIndex = 71;
            this.label6.Text = "SĐT";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Inter V Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(24, 58);
            this.label4.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(115, 19);
            this.label4.TabIndex = 70;
            this.label4.Text = "Mã Nhân Viên";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Inter V Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(348, 127);
            this.label7.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(82, 19);
            this.label7.TabIndex = 75;
            this.label7.Text = "Mật Khẩu";
            // 
            // txt_TimKiem
            // 
            this.txt_TimKiem.AcceptsReturn = false;
            this.txt_TimKiem.AcceptsTab = false;
            this.txt_TimKiem.AnimationSpeed = 200;
            this.txt_TimKiem.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_TimKiem.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_TimKiem.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(88)))), ((int)(((byte)(88)))));
            this.txt_TimKiem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_TimKiem.BackgroundImage")));
            this.txt_TimKiem.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_TimKiem.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_TimKiem.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_TimKiem.BorderColorIdle = System.Drawing.Color.Black;
            this.txt_TimKiem.BorderRadius = 30;
            this.txt_TimKiem.BorderThickness = 1;
            this.txt_TimKiem.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_TimKiem.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_TimKiem.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txt_TimKiem.DefaultText = "";
            this.txt_TimKiem.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(88)))), ((int)(((byte)(88)))));
            this.txt_TimKiem.HideSelection = true;
            this.txt_TimKiem.IconLeft = null;
            this.txt_TimKiem.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_TimKiem.IconPadding = 10;
            this.txt_TimKiem.IconRight = ((System.Drawing.Image)(resources.GetObject("txt_TimKiem.IconRight")));
            this.txt_TimKiem.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_TimKiem.Lines = new string[0];
            this.txt_TimKiem.Location = new System.Drawing.Point(278, 3);
            this.txt_TimKiem.MaxLength = 32767;
            this.txt_TimKiem.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_TimKiem.Modified = false;
            this.txt_TimKiem.Multiline = false;
            this.txt_TimKiem.Name = "txt_TimKiem";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_TimKiem.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_TimKiem.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_TimKiem.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Black;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(88)))), ((int)(((byte)(88)))));
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_TimKiem.OnIdleState = stateProperties24;
            this.txt_TimKiem.Padding = new System.Windows.Forms.Padding(3);
            this.txt_TimKiem.PasswordChar = '\0';
            this.txt_TimKiem.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txt_TimKiem.PlaceholderText = "Tìm kiếm theo tên";
            this.txt_TimKiem.ReadOnly = false;
            this.txt_TimKiem.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_TimKiem.SelectedText = "";
            this.txt_TimKiem.SelectionLength = 0;
            this.txt_TimKiem.SelectionStart = 0;
            this.txt_TimKiem.ShortcutsEnabled = true;
            this.txt_TimKiem.Size = new System.Drawing.Size(260, 42);
            this.txt_TimKiem.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txt_TimKiem.TabIndex = 0;
            this.txt_TimKiem.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_TimKiem.TextMarginBottom = 0;
            this.txt_TimKiem.TextMarginLeft = 3;
            this.txt_TimKiem.TextMarginTop = 0;
            this.txt_TimKiem.TextPlaceholder = "Tìm kiếm theo tên";
            this.txt_TimKiem.UseSystemPasswordChar = false;
            this.txt_TimKiem.WordWrap = true;
            this.txt_TimKiem.TextChanged += new System.EventHandler(this.txt_TimKiem_TextChanged);
            // 
            // QuanLyNhanVien
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.IndianRed;
            this.Controls.Add(this.txt_TimKiem);
            this.Controls.Add(this.btn_Luu);
            this.Controls.Add(this.btn_Them);
            this.Controls.Add(this.btn_Sua);
            this.Controls.Add(this.txt_MatKhau);
            this.Controls.Add(this.txt_DN);
            this.Controls.Add(this.txt_SDT);
            this.Controls.Add(this.txt_Ten);
            this.Controls.Add(this.txt_MaNV);
            this.Controls.Add(this.btn_Moi);
            this.Controls.Add(this.cb_GioiTinh);
            this.Controls.Add(this.btn_Xoa);
            this.Controls.Add(this.grid_NhanVien);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label7);
            this.Name = "QuanLyNhanVien";
            this.Size = new System.Drawing.Size(852, 530);
            this.Load += new System.EventHandler(this.UserControl1_Load);
            ((System.ComponentModel.ISupportInitialize)(this.grid_NhanVien)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_Luu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_Them;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_Sua;
        private Bunifu.UI.WinForms.BunifuTextBox txt_MatKhau;
        private Bunifu.UI.WinForms.BunifuTextBox txt_DN;
        private Bunifu.UI.WinForms.BunifuTextBox txt_SDT;
        private Bunifu.UI.WinForms.BunifuTextBox txt_Ten;
        private Bunifu.UI.WinForms.BunifuTextBox txt_MaNV;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_Moi;
        private Bunifu.UI.WinForms.BunifuDropdown cb_GioiTinh;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuDataGridView grid_NhanVien;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_Xoa;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox txt_TimKiem;
        private System.Windows.Forms.DataGridViewTextBoxColumn MaNV;
        private System.Windows.Forms.DataGridViewTextBoxColumn TenNV;
        private System.Windows.Forms.DataGridViewTextBoxColumn GioiTinh;
        private System.Windows.Forms.DataGridViewTextBoxColumn SDT;
        private System.Windows.Forms.DataGridViewTextBoxColumn TenNguoiDung;
        private System.Windows.Forms.DataGridViewTextBoxColumn MatKhau;
    }
}
